/**
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.stateDef.impl;

import java.util.Collection;

import nl.sudohenk.xtext.stateDef.MessageStructureDatatype;
import nl.sudohenk.xtext.stateDef.MessageStructureStruct;
import nl.sudohenk.xtext.stateDef.StateDefPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Message Structure Datatype</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.sudohenk.xtext.stateDef.impl.MessageStructureDatatypeImpl#getHexVal <em>Hex Val</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.impl.MessageStructureDatatypeImpl#getEnumVal <em>Enum Val</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.impl.MessageStructureDatatypeImpl#getStructVal <em>Struct Val</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.impl.MessageStructureDatatypeImpl#getArrayVal <em>Array Val</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MessageStructureDatatypeImpl extends MinimalEObjectImpl.Container implements MessageStructureDatatype
{
  /**
   * The default value of the '{@link #getHexVal() <em>Hex Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHexVal()
   * @generated
   * @ordered
   */
  protected static final String HEX_VAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHexVal() <em>Hex Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHexVal()
   * @generated
   * @ordered
   */
  protected String hexVal = HEX_VAL_EDEFAULT;

  /**
   * The default value of the '{@link #getEnumVal() <em>Enum Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumVal()
   * @generated
   * @ordered
   */
  protected static final String ENUM_VAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnumVal() <em>Enum Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumVal()
   * @generated
   * @ordered
   */
  protected String enumVal = ENUM_VAL_EDEFAULT;

  /**
   * The cached value of the '{@link #getStructVal() <em>Struct Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStructVal()
   * @generated
   * @ordered
   */
  protected MessageStructureStruct structVal;

  /**
   * The cached value of the '{@link #getArrayVal() <em>Array Val</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArrayVal()
   * @generated
   * @ordered
   */
  protected EList<MessageStructureDatatype> arrayVal;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MessageStructureDatatypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StateDefPackage.Literals.MESSAGE_STRUCTURE_DATATYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getHexVal()
  {
    return hexVal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHexVal(String newHexVal)
  {
    String oldHexVal = hexVal;
    hexVal = newHexVal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__HEX_VAL, oldHexVal, hexVal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getEnumVal()
  {
    return enumVal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnumVal(String newEnumVal)
  {
    String oldEnumVal = enumVal;
    enumVal = newEnumVal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__ENUM_VAL, oldEnumVal, enumVal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MessageStructureStruct getStructVal()
  {
    return structVal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStructVal(MessageStructureStruct newStructVal, NotificationChain msgs)
  {
    MessageStructureStruct oldStructVal = structVal;
    structVal = newStructVal;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__STRUCT_VAL, oldStructVal, newStructVal);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStructVal(MessageStructureStruct newStructVal)
  {
    if (newStructVal != structVal)
    {
      NotificationChain msgs = null;
      if (structVal != null)
        msgs = ((InternalEObject)structVal).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__STRUCT_VAL, null, msgs);
      if (newStructVal != null)
        msgs = ((InternalEObject)newStructVal).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__STRUCT_VAL, null, msgs);
      msgs = basicSetStructVal(newStructVal, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__STRUCT_VAL, newStructVal, newStructVal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<MessageStructureDatatype> getArrayVal()
  {
    if (arrayVal == null)
    {
      arrayVal = new EObjectContainmentEList<MessageStructureDatatype>(MessageStructureDatatype.class, this, StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__ARRAY_VAL);
    }
    return arrayVal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__STRUCT_VAL:
        return basicSetStructVal(null, msgs);
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__ARRAY_VAL:
        return ((InternalEList<?>)getArrayVal()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__HEX_VAL:
        return getHexVal();
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__ENUM_VAL:
        return getEnumVal();
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__STRUCT_VAL:
        return getStructVal();
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__ARRAY_VAL:
        return getArrayVal();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__HEX_VAL:
        setHexVal((String)newValue);
        return;
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__ENUM_VAL:
        setEnumVal((String)newValue);
        return;
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__STRUCT_VAL:
        setStructVal((MessageStructureStruct)newValue);
        return;
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__ARRAY_VAL:
        getArrayVal().clear();
        getArrayVal().addAll((Collection<? extends MessageStructureDatatype>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__HEX_VAL:
        setHexVal(HEX_VAL_EDEFAULT);
        return;
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__ENUM_VAL:
        setEnumVal(ENUM_VAL_EDEFAULT);
        return;
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__STRUCT_VAL:
        setStructVal((MessageStructureStruct)null);
        return;
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__ARRAY_VAL:
        getArrayVal().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__HEX_VAL:
        return HEX_VAL_EDEFAULT == null ? hexVal != null : !HEX_VAL_EDEFAULT.equals(hexVal);
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__ENUM_VAL:
        return ENUM_VAL_EDEFAULT == null ? enumVal != null : !ENUM_VAL_EDEFAULT.equals(enumVal);
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__STRUCT_VAL:
        return structVal != null;
      case StateDefPackage.MESSAGE_STRUCTURE_DATATYPE__ARRAY_VAL:
        return arrayVal != null && !arrayVal.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (hexVal: ");
    result.append(hexVal);
    result.append(", enumVal: ");
    result.append(enumVal);
    result.append(')');
    return result.toString();
  }

} //MessageStructureDatatypeImpl
