/**
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.ui.contentassist;

import nl.sudohenk.xtext.ui.contentassist.AbstractStateDefProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class StateDefProposalProvider extends AbstractStateDefProposalProvider {
}
