/*
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.ui;

import com.google.inject.Injector;
import nl.sudohenk.xtext.StateDef.ui.internal.StateDefActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StateDefExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(StateDefActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		StateDefActivator activator = StateDefActivator.getInstance();
		return activator != null ? activator.getInjector(StateDefActivator.NL_MAIKEL_XTEXT_STATEDEF) : null;
	}

}
