/*
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStateDefScopeProvider extends DelegatingScopeProvider {
}
