/**
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.validation;

import nl.sudohenk.xtext.validation.AbstractStateDefValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class StateDefValidator extends AbstractStateDefValidator {
}
