/*
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StateDefAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("nl/sudohenk/xtext/parser/antlr/internal/InternalStateDef.tokens");
	}
}
