/**
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.stateDef;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message Struct Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getDataType <em>Data Type</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getRefType <em>Ref Type</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getName <em>Name</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getByteRange <em>Byte Range</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getByteSize <em>Byte Size</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getDataAssignment <em>Data Assignment</em>}</li>
 * </ul>
 *
 * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getMessageStructEntry()
 * @model
 * @generated
 */
public interface MessageStructEntry extends EObject
{
  /**
   * Returns the value of the '<em><b>Data Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Type</em>' attribute.
   * @see #setDataType(String)
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getMessageStructEntry_DataType()
   * @model
   * @generated
   */
  String getDataType();

  /**
   * Sets the value of the '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getDataType <em>Data Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Type</em>' attribute.
   * @see #getDataType()
   * @generated
   */
  void setDataType(String value);

  /**
   * Returns the value of the '<em><b>Ref Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref Type</em>' attribute.
   * @see #setRefType(String)
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getMessageStructEntry_RefType()
   * @model
   * @generated
   */
  String getRefType();

  /**
   * Sets the value of the '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getRefType <em>Ref Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref Type</em>' attribute.
   * @see #getRefType()
   * @generated
   */
  void setRefType(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getMessageStructEntry_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Byte Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Byte Range</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Byte Range</em>' containment reference.
   * @see #setByteRange(MessageByteRange)
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getMessageStructEntry_ByteRange()
   * @model containment="true"
   * @generated
   */
  MessageByteRange getByteRange();

  /**
   * Sets the value of the '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getByteRange <em>Byte Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Byte Range</em>' containment reference.
   * @see #getByteRange()
   * @generated
   */
  void setByteRange(MessageByteRange value);

  /**
   * Returns the value of the '<em><b>Byte Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Byte Size</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Byte Size</em>' containment reference.
   * @see #setByteSize(MessageByteArray)
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getMessageStructEntry_ByteSize()
   * @model containment="true"
   * @generated
   */
  MessageByteArray getByteSize();

  /**
   * Sets the value of the '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getByteSize <em>Byte Size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Byte Size</em>' containment reference.
   * @see #getByteSize()
   * @generated
   */
  void setByteSize(MessageByteArray value);

  /**
   * Returns the value of the '<em><b>Data Assignment</b></em>' containment reference list.
   * The list contents are of type {@link nl.sudohenk.xtext.stateDef.MessageStructureDatatype}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data Assignment</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Assignment</em>' containment reference list.
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getMessageStructEntry_DataAssignment()
   * @model containment="true"
   * @generated
   */
  EList<MessageStructureDatatype> getDataAssignment();

} // MessageStructEntry
