/**
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.stateDef;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see nl.sudohenk.xtext.stateDef.StateDefPackage
 * @generated
 */
public interface StateDefFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StateDefFactory eINSTANCE = nl.sudohenk.xtext.stateDef.impl.StateDefFactoryImpl.init();

  /**
   * Returns a new object of class '<em>State Machine</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Machine</em>'.
   * @generated
   */
  StateMachine createStateMachine();

  /**
   * Returns a new object of class '<em>State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State</em>'.
   * @generated
   */
  State createState();

  /**
   * Returns a new object of class '<em>Message Transition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Transition</em>'.
   * @generated
   */
  MessageTransition createMessageTransition();

  /**
   * Returns a new object of class '<em>Message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message</em>'.
   * @generated
   */
  Message createMessage();

  /**
   * Returns a new object of class '<em>Message Struct</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Struct</em>'.
   * @generated
   */
  MessageStruct createMessageStruct();

  /**
   * Returns a new object of class '<em>Message Struct Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Struct Entry</em>'.
   * @generated
   */
  MessageStructEntry createMessageStructEntry();

  /**
   * Returns a new object of class '<em>Message Byte Range</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Byte Range</em>'.
   * @generated
   */
  MessageByteRange createMessageByteRange();

  /**
   * Returns a new object of class '<em>Message Byte Array</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Byte Array</em>'.
   * @generated
   */
  MessageByteArray createMessageByteArray();

  /**
   * Returns a new object of class '<em>Message Structure Struct</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Structure Struct</em>'.
   * @generated
   */
  MessageStructureStruct createMessageStructureStruct();

  /**
   * Returns a new object of class '<em>Message Structure Datatype</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Structure Datatype</em>'.
   * @generated
   */
  MessageStructureDatatype createMessageStructureDatatype();

  /**
   * Returns a new object of class '<em>Message Enum</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Enum</em>'.
   * @generated
   */
  MessageEnum createMessageEnum();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  StateDefPackage getStateDefPackage();

} //StateDefFactory
