/**
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.stateDef;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State Machine</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.sudohenk.xtext.stateDef.StateMachine#getName <em>Name</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.StateMachine#getGlobalStructs <em>Global Structs</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.StateMachine#getGlobalEnums <em>Global Enums</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.StateMachine#getMessages <em>Messages</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.StateMachine#getInitState <em>Init State</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.StateMachine#getStates <em>States</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.StateMachine#getTransitions <em>Transitions</em>}</li>
 *   <li>{@link nl.sudohenk.xtext.stateDef.StateMachine#getEndState <em>End State</em>}</li>
 * </ul>
 *
 * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getStateMachine()
 * @model
 * @generated
 */
public interface StateMachine extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getStateMachine_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link nl.sudohenk.xtext.stateDef.StateMachine#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Global Structs</b></em>' containment reference list.
   * The list contents are of type {@link nl.sudohenk.xtext.stateDef.MessageStruct}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Global Structs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global Structs</em>' containment reference list.
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getStateMachine_GlobalStructs()
   * @model containment="true"
   * @generated
   */
  EList<MessageStruct> getGlobalStructs();

  /**
   * Returns the value of the '<em><b>Global Enums</b></em>' containment reference list.
   * The list contents are of type {@link nl.sudohenk.xtext.stateDef.MessageEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Global Enums</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global Enums</em>' containment reference list.
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getStateMachine_GlobalEnums()
   * @model containment="true"
   * @generated
   */
  EList<MessageEnum> getGlobalEnums();

  /**
   * Returns the value of the '<em><b>Messages</b></em>' containment reference list.
   * The list contents are of type {@link nl.sudohenk.xtext.stateDef.Message}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Messages</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Messages</em>' containment reference list.
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getStateMachine_Messages()
   * @model containment="true"
   * @generated
   */
  EList<Message> getMessages();

  /**
   * Returns the value of the '<em><b>Init State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init State</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init State</em>' containment reference.
   * @see #setInitState(State)
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getStateMachine_InitState()
   * @model containment="true"
   * @generated
   */
  State getInitState();

  /**
   * Sets the value of the '{@link nl.sudohenk.xtext.stateDef.StateMachine#getInitState <em>Init State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init State</em>' containment reference.
   * @see #getInitState()
   * @generated
   */
  void setInitState(State value);

  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link nl.sudohenk.xtext.stateDef.State}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>States</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getStateMachine_States()
   * @model containment="true"
   * @generated
   */
  EList<State> getStates();

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link nl.sudohenk.xtext.stateDef.MessageTransition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Transitions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getStateMachine_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<MessageTransition> getTransitions();

  /**
   * Returns the value of the '<em><b>End State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End State</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End State</em>' containment reference.
   * @see #setEndState(State)
   * @see nl.sudohenk.xtext.stateDef.StateDefPackage#getStateMachine_EndState()
   * @model containment="true"
   * @generated
   */
  State getEndState();

  /**
   * Sets the value of the '{@link nl.sudohenk.xtext.stateDef.StateMachine#getEndState <em>End State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End State</em>' containment reference.
   * @see #getEndState()
   * @generated
   */
  void setEndState(State value);

} // StateMachine
