/**
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.stateDef;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see nl.sudohenk.xtext.stateDef.StateDefFactory
 * @model kind="package"
 * @generated
 */
public interface StateDefPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "stateDef";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sudohenk.nl/xtext/StateDef";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "stateDef";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StateDefPackage eINSTANCE = nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl.init();

  /**
   * The meta object id for the '{@link nl.sudohenk.xtext.stateDef.impl.StateMachineImpl <em>State Machine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.sudohenk.xtext.stateDef.impl.StateMachineImpl
   * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getStateMachine()
   * @generated
   */
  int STATE_MACHINE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__NAME = 0;

  /**
   * The feature id for the '<em><b>Global Structs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__GLOBAL_STRUCTS = 1;

  /**
   * The feature id for the '<em><b>Global Enums</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__GLOBAL_ENUMS = 2;

  /**
   * The feature id for the '<em><b>Messages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__MESSAGES = 3;

  /**
   * The feature id for the '<em><b>Init State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__INIT_STATE = 4;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__STATES = 5;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__TRANSITIONS = 6;

  /**
   * The feature id for the '<em><b>End State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__END_STATE = 7;

  /**
   * The number of structural features of the '<em>State Machine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link nl.sudohenk.xtext.stateDef.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.sudohenk.xtext.stateDef.impl.StateImpl
   * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getState()
   * @generated
   */
  int STATE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 0;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageTransitionImpl <em>Message Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.sudohenk.xtext.stateDef.impl.MessageTransitionImpl
   * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageTransition()
   * @generated
   */
  int MESSAGE_TRANSITION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_TRANSITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Current State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_TRANSITION__CURRENT_STATE = 1;

  /**
   * The feature id for the '<em><b>Any State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_TRANSITION__ANY_STATE = 2;

  /**
   * The feature id for the '<em><b>Received Messages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_TRANSITION__RECEIVED_MESSAGES = 3;

  /**
   * The feature id for the '<em><b>Sent Messages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_TRANSITION__SENT_MESSAGES = 4;

  /**
   * The feature id for the '<em><b>Next State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_TRANSITION__NEXT_STATE = 5;

  /**
   * The number of structural features of the '<em>Message Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_TRANSITION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageImpl <em>Message</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.sudohenk.xtext.stateDef.impl.MessageImpl
   * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessage()
   * @generated
   */
  int MESSAGE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Struct Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__STRUCT_ENTRIES = 1;

  /**
   * The number of structural features of the '<em>Message</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageStructImpl <em>Message Struct</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.sudohenk.xtext.stateDef.impl.MessageStructImpl
   * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageStruct()
   * @generated
   */
  int MESSAGE_STRUCT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCT__NAME = 0;

  /**
   * The feature id for the '<em><b>Struct Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCT__STRUCT_ENTRIES = 1;

  /**
   * The number of structural features of the '<em>Message Struct</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageStructEntryImpl <em>Message Struct Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.sudohenk.xtext.stateDef.impl.MessageStructEntryImpl
   * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageStructEntry()
   * @generated
   */
  int MESSAGE_STRUCT_ENTRY = 5;

  /**
   * The feature id for the '<em><b>Data Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCT_ENTRY__DATA_TYPE = 0;

  /**
   * The feature id for the '<em><b>Ref Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCT_ENTRY__REF_TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCT_ENTRY__NAME = 2;

  /**
   * The feature id for the '<em><b>Byte Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCT_ENTRY__BYTE_RANGE = 3;

  /**
   * The feature id for the '<em><b>Byte Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCT_ENTRY__BYTE_SIZE = 4;

  /**
   * The feature id for the '<em><b>Data Assignment</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCT_ENTRY__DATA_ASSIGNMENT = 5;

  /**
   * The number of structural features of the '<em>Message Struct Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCT_ENTRY_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageByteRangeImpl <em>Message Byte Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.sudohenk.xtext.stateDef.impl.MessageByteRangeImpl
   * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageByteRange()
   * @generated
   */
  int MESSAGE_BYTE_RANGE = 6;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_BYTE_RANGE__START = 0;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_BYTE_RANGE__END = 1;

  /**
   * The number of structural features of the '<em>Message Byte Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_BYTE_RANGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageByteArrayImpl <em>Message Byte Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.sudohenk.xtext.stateDef.impl.MessageByteArrayImpl
   * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageByteArray()
   * @generated
   */
  int MESSAGE_BYTE_ARRAY = 7;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_BYTE_ARRAY__SIZE = 0;

  /**
   * The number of structural features of the '<em>Message Byte Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_BYTE_ARRAY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageStructureStructImpl <em>Message Structure Struct</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.sudohenk.xtext.stateDef.impl.MessageStructureStructImpl
   * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageStructureStruct()
   * @generated
   */
  int MESSAGE_STRUCTURE_STRUCT = 8;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCTURE_STRUCT__VALUES = 0;

  /**
   * The number of structural features of the '<em>Message Structure Struct</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCTURE_STRUCT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageStructureDatatypeImpl <em>Message Structure Datatype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.sudohenk.xtext.stateDef.impl.MessageStructureDatatypeImpl
   * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageStructureDatatype()
   * @generated
   */
  int MESSAGE_STRUCTURE_DATATYPE = 9;

  /**
   * The feature id for the '<em><b>Hex Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCTURE_DATATYPE__HEX_VAL = 0;

  /**
   * The feature id for the '<em><b>Enum Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCTURE_DATATYPE__ENUM_VAL = 1;

  /**
   * The feature id for the '<em><b>Struct Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCTURE_DATATYPE__STRUCT_VAL = 2;

  /**
   * The feature id for the '<em><b>Array Val</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCTURE_DATATYPE__ARRAY_VAL = 3;

  /**
   * The number of structural features of the '<em>Message Structure Datatype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_STRUCTURE_DATATYPE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageEnumImpl <em>Message Enum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.sudohenk.xtext.stateDef.impl.MessageEnumImpl
   * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageEnum()
   * @generated
   */
  int MESSAGE_ENUM = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_ENUM__NAME = 0;

  /**
   * The feature id for the '<em><b>Names</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_ENUM__NAMES = 1;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_ENUM__VALUES = 2;

  /**
   * The number of structural features of the '<em>Message Enum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_ENUM_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link nl.sudohenk.xtext.stateDef.StateMachine <em>State Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State Machine</em>'.
   * @see nl.sudohenk.xtext.stateDef.StateMachine
   * @generated
   */
  EClass getStateMachine();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.StateMachine#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see nl.sudohenk.xtext.stateDef.StateMachine#getName()
   * @see #getStateMachine()
   * @generated
   */
  EAttribute getStateMachine_Name();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.StateMachine#getGlobalStructs <em>Global Structs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Global Structs</em>'.
   * @see nl.sudohenk.xtext.stateDef.StateMachine#getGlobalStructs()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_GlobalStructs();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.StateMachine#getGlobalEnums <em>Global Enums</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Global Enums</em>'.
   * @see nl.sudohenk.xtext.stateDef.StateMachine#getGlobalEnums()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_GlobalEnums();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.StateMachine#getMessages <em>Messages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Messages</em>'.
   * @see nl.sudohenk.xtext.stateDef.StateMachine#getMessages()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_Messages();

  /**
   * Returns the meta object for the containment reference '{@link nl.sudohenk.xtext.stateDef.StateMachine#getInitState <em>Init State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init State</em>'.
   * @see nl.sudohenk.xtext.stateDef.StateMachine#getInitState()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_InitState();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.StateMachine#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see nl.sudohenk.xtext.stateDef.StateMachine#getStates()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_States();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.StateMachine#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see nl.sudohenk.xtext.stateDef.StateMachine#getTransitions()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_Transitions();

  /**
   * Returns the meta object for the containment reference '{@link nl.sudohenk.xtext.stateDef.StateMachine#getEndState <em>End State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>End State</em>'.
   * @see nl.sudohenk.xtext.stateDef.StateMachine#getEndState()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_EndState();

  /**
   * Returns the meta object for class '{@link nl.sudohenk.xtext.stateDef.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see nl.sudohenk.xtext.stateDef.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see nl.sudohenk.xtext.stateDef.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for class '{@link nl.sudohenk.xtext.stateDef.MessageTransition <em>Message Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Transition</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageTransition
   * @generated
   */
  EClass getMessageTransition();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageTransition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageTransition#getName()
   * @see #getMessageTransition()
   * @generated
   */
  EAttribute getMessageTransition_Name();

  /**
   * Returns the meta object for the containment reference '{@link nl.sudohenk.xtext.stateDef.MessageTransition#getCurrentState <em>Current State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Current State</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageTransition#getCurrentState()
   * @see #getMessageTransition()
   * @generated
   */
  EReference getMessageTransition_CurrentState();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageTransition#getAnyState <em>Any State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Any State</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageTransition#getAnyState()
   * @see #getMessageTransition()
   * @generated
   */
  EAttribute getMessageTransition_AnyState();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.MessageTransition#getReceivedMessages <em>Received Messages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Received Messages</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageTransition#getReceivedMessages()
   * @see #getMessageTransition()
   * @generated
   */
  EReference getMessageTransition_ReceivedMessages();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.MessageTransition#getSentMessages <em>Sent Messages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sent Messages</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageTransition#getSentMessages()
   * @see #getMessageTransition()
   * @generated
   */
  EReference getMessageTransition_SentMessages();

  /**
   * Returns the meta object for the containment reference '{@link nl.sudohenk.xtext.stateDef.MessageTransition#getNextState <em>Next State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Next State</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageTransition#getNextState()
   * @see #getMessageTransition()
   * @generated
   */
  EReference getMessageTransition_NextState();

  /**
   * Returns the meta object for class '{@link nl.sudohenk.xtext.stateDef.Message <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message</em>'.
   * @see nl.sudohenk.xtext.stateDef.Message
   * @generated
   */
  EClass getMessage();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.Message#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see nl.sudohenk.xtext.stateDef.Message#getName()
   * @see #getMessage()
   * @generated
   */
  EAttribute getMessage_Name();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.Message#getStructEntries <em>Struct Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Struct Entries</em>'.
   * @see nl.sudohenk.xtext.stateDef.Message#getStructEntries()
   * @see #getMessage()
   * @generated
   */
  EReference getMessage_StructEntries();

  /**
   * Returns the meta object for class '{@link nl.sudohenk.xtext.stateDef.MessageStruct <em>Message Struct</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Struct</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStruct
   * @generated
   */
  EClass getMessageStruct();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageStruct#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStruct#getName()
   * @see #getMessageStruct()
   * @generated
   */
  EAttribute getMessageStruct_Name();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.MessageStruct#getStructEntries <em>Struct Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Struct Entries</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStruct#getStructEntries()
   * @see #getMessageStruct()
   * @generated
   */
  EReference getMessageStruct_StructEntries();

  /**
   * Returns the meta object for class '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry <em>Message Struct Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Struct Entry</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructEntry
   * @generated
   */
  EClass getMessageStructEntry();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getDataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data Type</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructEntry#getDataType()
   * @see #getMessageStructEntry()
   * @generated
   */
  EAttribute getMessageStructEntry_DataType();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getRefType <em>Ref Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ref Type</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructEntry#getRefType()
   * @see #getMessageStructEntry()
   * @generated
   */
  EAttribute getMessageStructEntry_RefType();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructEntry#getName()
   * @see #getMessageStructEntry()
   * @generated
   */
  EAttribute getMessageStructEntry_Name();

  /**
   * Returns the meta object for the containment reference '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getByteRange <em>Byte Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Byte Range</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructEntry#getByteRange()
   * @see #getMessageStructEntry()
   * @generated
   */
  EReference getMessageStructEntry_ByteRange();

  /**
   * Returns the meta object for the containment reference '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getByteSize <em>Byte Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Byte Size</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructEntry#getByteSize()
   * @see #getMessageStructEntry()
   * @generated
   */
  EReference getMessageStructEntry_ByteSize();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.MessageStructEntry#getDataAssignment <em>Data Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data Assignment</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructEntry#getDataAssignment()
   * @see #getMessageStructEntry()
   * @generated
   */
  EReference getMessageStructEntry_DataAssignment();

  /**
   * Returns the meta object for class '{@link nl.sudohenk.xtext.stateDef.MessageByteRange <em>Message Byte Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Byte Range</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageByteRange
   * @generated
   */
  EClass getMessageByteRange();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageByteRange#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageByteRange#getStart()
   * @see #getMessageByteRange()
   * @generated
   */
  EAttribute getMessageByteRange_Start();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageByteRange#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageByteRange#getEnd()
   * @see #getMessageByteRange()
   * @generated
   */
  EAttribute getMessageByteRange_End();

  /**
   * Returns the meta object for class '{@link nl.sudohenk.xtext.stateDef.MessageByteArray <em>Message Byte Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Byte Array</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageByteArray
   * @generated
   */
  EClass getMessageByteArray();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageByteArray#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageByteArray#getSize()
   * @see #getMessageByteArray()
   * @generated
   */
  EAttribute getMessageByteArray_Size();

  /**
   * Returns the meta object for class '{@link nl.sudohenk.xtext.stateDef.MessageStructureStruct <em>Message Structure Struct</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Structure Struct</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructureStruct
   * @generated
   */
  EClass getMessageStructureStruct();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.MessageStructureStruct#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructureStruct#getValues()
   * @see #getMessageStructureStruct()
   * @generated
   */
  EReference getMessageStructureStruct_Values();

  /**
   * Returns the meta object for class '{@link nl.sudohenk.xtext.stateDef.MessageStructureDatatype <em>Message Structure Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Structure Datatype</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructureDatatype
   * @generated
   */
  EClass getMessageStructureDatatype();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageStructureDatatype#getHexVal <em>Hex Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hex Val</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructureDatatype#getHexVal()
   * @see #getMessageStructureDatatype()
   * @generated
   */
  EAttribute getMessageStructureDatatype_HexVal();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageStructureDatatype#getEnumVal <em>Enum Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Enum Val</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructureDatatype#getEnumVal()
   * @see #getMessageStructureDatatype()
   * @generated
   */
  EAttribute getMessageStructureDatatype_EnumVal();

  /**
   * Returns the meta object for the containment reference '{@link nl.sudohenk.xtext.stateDef.MessageStructureDatatype#getStructVal <em>Struct Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Struct Val</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructureDatatype#getStructVal()
   * @see #getMessageStructureDatatype()
   * @generated
   */
  EReference getMessageStructureDatatype_StructVal();

  /**
   * Returns the meta object for the containment reference list '{@link nl.sudohenk.xtext.stateDef.MessageStructureDatatype#getArrayVal <em>Array Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Array Val</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageStructureDatatype#getArrayVal()
   * @see #getMessageStructureDatatype()
   * @generated
   */
  EReference getMessageStructureDatatype_ArrayVal();

  /**
   * Returns the meta object for class '{@link nl.sudohenk.xtext.stateDef.MessageEnum <em>Message Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Enum</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageEnum
   * @generated
   */
  EClass getMessageEnum();

  /**
   * Returns the meta object for the attribute '{@link nl.sudohenk.xtext.stateDef.MessageEnum#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageEnum#getName()
   * @see #getMessageEnum()
   * @generated
   */
  EAttribute getMessageEnum_Name();

  /**
   * Returns the meta object for the attribute list '{@link nl.sudohenk.xtext.stateDef.MessageEnum#getNames <em>Names</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Names</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageEnum#getNames()
   * @see #getMessageEnum()
   * @generated
   */
  EAttribute getMessageEnum_Names();

  /**
   * Returns the meta object for the attribute list '{@link nl.sudohenk.xtext.stateDef.MessageEnum#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see nl.sudohenk.xtext.stateDef.MessageEnum#getValues()
   * @see #getMessageEnum()
   * @generated
   */
  EAttribute getMessageEnum_Values();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  StateDefFactory getStateDefFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link nl.sudohenk.xtext.stateDef.impl.StateMachineImpl <em>State Machine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.sudohenk.xtext.stateDef.impl.StateMachineImpl
     * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getStateMachine()
     * @generated
     */
    EClass STATE_MACHINE = eINSTANCE.getStateMachine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE_MACHINE__NAME = eINSTANCE.getStateMachine_Name();

    /**
     * The meta object literal for the '<em><b>Global Structs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__GLOBAL_STRUCTS = eINSTANCE.getStateMachine_GlobalStructs();

    /**
     * The meta object literal for the '<em><b>Global Enums</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__GLOBAL_ENUMS = eINSTANCE.getStateMachine_GlobalEnums();

    /**
     * The meta object literal for the '<em><b>Messages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__MESSAGES = eINSTANCE.getStateMachine_Messages();

    /**
     * The meta object literal for the '<em><b>Init State</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__INIT_STATE = eINSTANCE.getStateMachine_InitState();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__STATES = eINSTANCE.getStateMachine_States();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__TRANSITIONS = eINSTANCE.getStateMachine_Transitions();

    /**
     * The meta object literal for the '<em><b>End State</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__END_STATE = eINSTANCE.getStateMachine_EndState();

    /**
     * The meta object literal for the '{@link nl.sudohenk.xtext.stateDef.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.sudohenk.xtext.stateDef.impl.StateImpl
     * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageTransitionImpl <em>Message Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.sudohenk.xtext.stateDef.impl.MessageTransitionImpl
     * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageTransition()
     * @generated
     */
    EClass MESSAGE_TRANSITION = eINSTANCE.getMessageTransition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_TRANSITION__NAME = eINSTANCE.getMessageTransition_Name();

    /**
     * The meta object literal for the '<em><b>Current State</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_TRANSITION__CURRENT_STATE = eINSTANCE.getMessageTransition_CurrentState();

    /**
     * The meta object literal for the '<em><b>Any State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_TRANSITION__ANY_STATE = eINSTANCE.getMessageTransition_AnyState();

    /**
     * The meta object literal for the '<em><b>Received Messages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_TRANSITION__RECEIVED_MESSAGES = eINSTANCE.getMessageTransition_ReceivedMessages();

    /**
     * The meta object literal for the '<em><b>Sent Messages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_TRANSITION__SENT_MESSAGES = eINSTANCE.getMessageTransition_SentMessages();

    /**
     * The meta object literal for the '<em><b>Next State</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_TRANSITION__NEXT_STATE = eINSTANCE.getMessageTransition_NextState();

    /**
     * The meta object literal for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageImpl <em>Message</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.sudohenk.xtext.stateDef.impl.MessageImpl
     * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessage()
     * @generated
     */
    EClass MESSAGE = eINSTANCE.getMessage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE__NAME = eINSTANCE.getMessage_Name();

    /**
     * The meta object literal for the '<em><b>Struct Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE__STRUCT_ENTRIES = eINSTANCE.getMessage_StructEntries();

    /**
     * The meta object literal for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageStructImpl <em>Message Struct</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.sudohenk.xtext.stateDef.impl.MessageStructImpl
     * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageStruct()
     * @generated
     */
    EClass MESSAGE_STRUCT = eINSTANCE.getMessageStruct();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_STRUCT__NAME = eINSTANCE.getMessageStruct_Name();

    /**
     * The meta object literal for the '<em><b>Struct Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_STRUCT__STRUCT_ENTRIES = eINSTANCE.getMessageStruct_StructEntries();

    /**
     * The meta object literal for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageStructEntryImpl <em>Message Struct Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.sudohenk.xtext.stateDef.impl.MessageStructEntryImpl
     * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageStructEntry()
     * @generated
     */
    EClass MESSAGE_STRUCT_ENTRY = eINSTANCE.getMessageStructEntry();

    /**
     * The meta object literal for the '<em><b>Data Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_STRUCT_ENTRY__DATA_TYPE = eINSTANCE.getMessageStructEntry_DataType();

    /**
     * The meta object literal for the '<em><b>Ref Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_STRUCT_ENTRY__REF_TYPE = eINSTANCE.getMessageStructEntry_RefType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_STRUCT_ENTRY__NAME = eINSTANCE.getMessageStructEntry_Name();

    /**
     * The meta object literal for the '<em><b>Byte Range</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_STRUCT_ENTRY__BYTE_RANGE = eINSTANCE.getMessageStructEntry_ByteRange();

    /**
     * The meta object literal for the '<em><b>Byte Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_STRUCT_ENTRY__BYTE_SIZE = eINSTANCE.getMessageStructEntry_ByteSize();

    /**
     * The meta object literal for the '<em><b>Data Assignment</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_STRUCT_ENTRY__DATA_ASSIGNMENT = eINSTANCE.getMessageStructEntry_DataAssignment();

    /**
     * The meta object literal for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageByteRangeImpl <em>Message Byte Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.sudohenk.xtext.stateDef.impl.MessageByteRangeImpl
     * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageByteRange()
     * @generated
     */
    EClass MESSAGE_BYTE_RANGE = eINSTANCE.getMessageByteRange();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_BYTE_RANGE__START = eINSTANCE.getMessageByteRange_Start();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_BYTE_RANGE__END = eINSTANCE.getMessageByteRange_End();

    /**
     * The meta object literal for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageByteArrayImpl <em>Message Byte Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.sudohenk.xtext.stateDef.impl.MessageByteArrayImpl
     * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageByteArray()
     * @generated
     */
    EClass MESSAGE_BYTE_ARRAY = eINSTANCE.getMessageByteArray();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_BYTE_ARRAY__SIZE = eINSTANCE.getMessageByteArray_Size();

    /**
     * The meta object literal for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageStructureStructImpl <em>Message Structure Struct</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.sudohenk.xtext.stateDef.impl.MessageStructureStructImpl
     * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageStructureStruct()
     * @generated
     */
    EClass MESSAGE_STRUCTURE_STRUCT = eINSTANCE.getMessageStructureStruct();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_STRUCTURE_STRUCT__VALUES = eINSTANCE.getMessageStructureStruct_Values();

    /**
     * The meta object literal for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageStructureDatatypeImpl <em>Message Structure Datatype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.sudohenk.xtext.stateDef.impl.MessageStructureDatatypeImpl
     * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageStructureDatatype()
     * @generated
     */
    EClass MESSAGE_STRUCTURE_DATATYPE = eINSTANCE.getMessageStructureDatatype();

    /**
     * The meta object literal for the '<em><b>Hex Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_STRUCTURE_DATATYPE__HEX_VAL = eINSTANCE.getMessageStructureDatatype_HexVal();

    /**
     * The meta object literal for the '<em><b>Enum Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_STRUCTURE_DATATYPE__ENUM_VAL = eINSTANCE.getMessageStructureDatatype_EnumVal();

    /**
     * The meta object literal for the '<em><b>Struct Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_STRUCTURE_DATATYPE__STRUCT_VAL = eINSTANCE.getMessageStructureDatatype_StructVal();

    /**
     * The meta object literal for the '<em><b>Array Val</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_STRUCTURE_DATATYPE__ARRAY_VAL = eINSTANCE.getMessageStructureDatatype_ArrayVal();

    /**
     * The meta object literal for the '{@link nl.sudohenk.xtext.stateDef.impl.MessageEnumImpl <em>Message Enum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.sudohenk.xtext.stateDef.impl.MessageEnumImpl
     * @see nl.sudohenk.xtext.stateDef.impl.StateDefPackageImpl#getMessageEnum()
     * @generated
     */
    EClass MESSAGE_ENUM = eINSTANCE.getMessageEnum();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_ENUM__NAME = eINSTANCE.getMessageEnum_Name();

    /**
     * The meta object literal for the '<em><b>Names</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_ENUM__NAMES = eINSTANCE.getMessageEnum_Names();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_ENUM__VALUES = eINSTANCE.getMessageEnum_Values();

  }

} //StateDefPackage
