/*
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractStateDefValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(nl.sudohenk.xtext.stateDef.StateDefPackage.eINSTANCE);
		return result;
	}
}
