/**
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext;

import nl.sudohenk.xtext.StateDefStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class StateDefStandaloneSetup extends StateDefStandaloneSetupGenerated {
  public static void doSetup() {
    new StateDefStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
