/**
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.ui;

import nl.sudohenk.xtext.ui.AbstractStateDefUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class StateDefUiModule extends AbstractStateDefUiModule {
  public StateDefUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
