/**
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.ide;

import nl.sudohenk.xtext.ide.AbstractStateDefIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class StateDefIdeModule extends AbstractStateDefIdeModule {
}
