/**
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import nl.sudohenk.xtext.StateDefRuntimeModule;
import nl.sudohenk.xtext.StateDefStandaloneSetup;
import nl.sudohenk.xtext.ide.StateDefIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class StateDefIdeSetup extends StateDefStandaloneSetup {
  @Override
  public Injector createInjector() {
    StateDefRuntimeModule _stateDefRuntimeModule = new StateDefRuntimeModule();
    StateDefIdeModule _stateDefIdeModule = new StateDefIdeModule();
    return Guice.createInjector(Modules2.mixin(_stateDefRuntimeModule, _stateDefIdeModule));
  }
}
