/*
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StateDefStandaloneSetup extends StateDefStandaloneSetupGenerated {

	def static void doSetup() {
		new StateDefStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
