/*
 * generated by Xtext 2.14.0
 */
package nl.sudohenk.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class StateDefRuntimeModule extends AbstractStateDefRuntimeModule {
}
